before_script:
  - uname -a
  - curl https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein -o /usr/local/bin/lein
  - chmod +x /usr/local/bin/lein
  - mkdir -p /root/.lein
  - echo "{:user {:plugins [[lein-midje \"3.1.3\"]]}}" > /root/.lein/profiles.clj

test:
  script:
    - lein deps
    - lein midje
